language: c
os:
  - osx
  - linux

osx_image: xcode6.4

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p ~/gtk-gnutella && curl ${OBJECTSTORE_URL}gtk-gnutella-jhbuild.tar.bz2 | tar -jx  -C ~/gtk-gnutella || echo "Nothing prebuild" ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl https://git.gnome.org/browse/gtk-osx/plain/gtk-osx-build-setup.sh | sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cp -v osx/jhbuildrc-gtk-gnutella  ~/.jhbuildrc-gtk-gnutella && cp -v osx/gtk-gnutella.modules ~/gtk-gnutella.modules; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then git clone https://github.com/jralls/gtk-mac-bundler.git; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then JHB=gtk-gnutella ~/.local/bin/jhbuild --no-interact bootstrap 2>&1 | tee jhbuild-bootstrap.log | grep -e "\*\*\*" -e "Making" ; curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T jhbuild-bootstrap.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then JHB=gtk-gnutella ~/.local/bin/jhbuild --no-interact build meta-gtk-osx-bootstrap 2>&1 | tee jhbuild-meta-gtk-osx-bootstrap.log | grep -e "\*\*\*" -e "Making" ; curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T jhbuild-meta-gtk-osx-bootstrap.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar -jcf gtk-gnutella-jhbuild.tar.bz2 -C ~/gtk-gnutella inst && curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T gtk-gnutella-jhbuild.tar.bz2 || echo "Unable to save jhbuild build state 1." ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then JHB=gtk-gnutella ~/.local/bin/jhbuild --no-interact build meta-gtk-osx-core 2>&1 | tee jhbuild-meta-gtk-osx-core.log | grep -e "\*\*\*" -e "Making" ; curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T jhbuild-meta-gtk-osx-core.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar -jcf gtk-gnutella-jhbuild.tar.bz2 -C ~/gtk-gnutella inst && curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T gtk-gnutella-jhbuild.tar.bz2 || echo "Unable to save jhbuild build state 2." ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then JHB=gtk-gnutella ~/.local/bin/jhbuild --no-interact build 2>&1 | tee jhbuild-build.log | grep -e "\*\*\*" -e Making ; curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T jhbuild-build.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar -jcf gtk-gnutella-jhbuild.tar.bz2 -C ~/gtk-gnutella inst && curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T gtk-gnutella-jhbuild.tar.bz2 || echo "Unable to save jhbuild build state 3." ;fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pushd gtk-mac-bundler; make install; popd; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=$PATH:~/.local/bin; JHB=gtk-gnutella ~/.local/bin/jhbuild run ./build.sh --target=osxbundle 2>&1 | tee build.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL}build.log -T build.log ;fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build.sh; fi
  - src/lib/random-test
  - src/lib/sort-test
  - src/lib/filelock-test -ce foo
  - src/lib/filelock-test -cep foo
  - src/lib/launch-test
  - src/lib/spopen-test -p -r foo
  # Removing -F as the fork() call seems to disrupt the inter-thread signals,
  # messing-up with the file descriptor used to perform signalling?
  # Not critical since gtk-gnutella is not using thread_fork() currently.
  #		--RAM, 2015-02-22
  - src/lib/thread-test -ABCDEIKMNOPQRSVWX -T1 -c2 -z player,test_signals

after_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then for f in ~/Desktop/*dmg; do curl -X PUT --user ${OBJECTSTORE_USER}:${OBJECTSTORE_SECRET} ${OBJECTSTORE_URL} -T $f ;done ;fi

notifications:
  irc: "irc.freenode.net#gtk-gnutella"

